### ISSUE TITLE
CSP: null is dangerous

### ISSUE THREAD

**Issue by nothingismagick** [oSethoum/tauri-react-template#1]
Please consider putting it back, because it is easy to forget and opens up a MASSIVE can of worms.

https://github.com/oSethoum/tauri-react-template/blob/5ac42ddba7e440658c91deac4baddc5563b8496c/src-tauri/tauri.conf.json#L65

**Comment by oSethoum** [comment]
@nothingismagick it's the default config by Tauri creators, am not sure what to put back.

**Comment by nothingismagick** [comment]
oh no, that's us! 🏃‍♂️

**Comment by nothingismagick** [comment]
https://github.com/tauri-apps/tauri/commit/102a5e9bb83c5d8388dc9aedc7f03cc57bdae8cb

**Comment by nothingismagick** [comment]
I missed that change.
